### ISSUE TITLE
Hello Drone app crashes on Android emulator on clicking Install in 3DR Services popup

### ISSUE THREAD

**Issue by csathe** [DroidPlanner/DroneKit-Android#158]
Hello, 

I downloaded the 3DR Hello Drone Android app from Github , launched it, and it works fine on real devices with 3DR Services installed from Play Store. But I want it to run on Android emulator as well since I might not always have access to real devices. On Android emulator the app launches and a popup is shown prompting to install 3DR Services on the emulator. When I click Install, the app crashes on the emulator with the following: 

06-03 19:03:53.502    2768-2768/com.o3dr.hellodrone D/AndroidRuntime﹕ Shutting down VM

06-03 19:03:53.502    2768-2768/com.o3dr.hellodrone E/AndroidRuntime﹕ FATAL EXCEPTION: main

    Process: com.o3dr.hellodrone, PID: 2768

    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=org.droidplanner.services.android }

            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)

            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)

            at android.app.Activity.startActivityForResult(Activity.java:3745)

            at android.app.Activity.startActivityForResult(Activity.java:3706)

            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)

            at android.app.Activity.startActivity(Activity.java:4016)

            at android.app.Activity.startActivity(Activity.java:3984)

            at com.o3dr.android.client.utils.InstallServiceDialog$2.onClick(InstallServiceDialog.java:34)

            at android.view.View.performClick(View.java:4780)

            at android.view.View$PerformClick.run(View.java:19866)

            at android.os.Handler.handleCallback(Handler.java:739)

            at android.os.Handler.dispatchMessage(Handler.java:95)

            at android.os.Looper.loop(Looper.java:135)

            at android.app.ActivityThread.main(ActivityThread.java:5257)

            at java.lang.reflect.Method.invoke(Native Method)

            at java.lang.reflect.Method.invoke(Method.java:372)

            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Does anyone know a solution around this ? Please help !

![screen shot 2015-06-04 at 4 17 42 pm](https://cloud.githubusercontent.com/assets/8527193/7996648/6e4cdaa6-0ad7-11e5-8cb2-433632378993.png)

**Comment by ne0fhyk** [comment]
@csathe The app crashes because there's no installed play store app on the emulator. However, you can fix that issue by installing 3DR Services directly to the emulator.

You can either build the apk from the source code, or download it from the release page: https://github.com/DroidPlanner/DroneKit-Android/releases
